---
WORLD_NAME: reInvent2019_track
RACE_TYPE: OBJECT_AVOIDANCE
NUMBER_OF_OBSTACLES: 6
NUMBER_OF_BOT_CARS: 0
action_space_type: continuous
steering_angle:
  min: -30
  max: 30
speed:
  min: 0.5
  max: 4.0
